# This workflow will build a Java project with Maven, and cache/restore any dependencies
# to improve the workflow execution time.
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - milestone4-refactoring
  pull_request:
    branches:
      - milestone4-refactoring
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -Dmaven.test.skip=true -DskipITs -Dcheckstyle.skip=true -Drat.skip=true

      - name: Run storm-server tests except EvoSuite
        run: mvn -B -pl :storm-server "-Dtest=*Test,!*_ESTest" test -Dcheckstyle.skip=true -Drat.skip=true

      - name: Run storm-redis tests except EvoSuite
        run: mvn -B -pl :storm-redis "-Dtest=*Test,!*_ESTest" test -Dcheckstyle.skip=true -Drat.skip=true